import { Phase } from "@/types/tableTypes";

export const phaseLookUp: Phase[] = [
	{
		id: 1,
		phaseCode: "P1",
		phaseName: "Sales Handover",
		weightFactor: 0.5,
		createdAt: "",
		updatedAt: "",
	},
	{
		id: 2,
		phaseCode: "P2",
		phaseName: "Basic Design",
		weightFactor: 0.5,
		createdAt: "",
		updatedAt: "",
	},
	{
		id: 3,
		phaseCode: "P3",
		phaseName: "Detail Design",
		weightFactor: 1,
		createdAt: "",
		updatedAt: "",
	},
	{
		id: 4,
		phaseCode: "P4",
		phaseName: "Internal Test",
		weightFactor: 1,
		createdAt: "",
		updatedAt: "",
	},
	{
		id: 5,
		phaseCode: "P5",
		phaseName: "Factory Acceptance Test (FAT)",
		weightFactor: 1.2,
		createdAt: "",
		updatedAt: "",
	},
	{
		id: 6,
		phaseCode: "P6",
		phaseName: "FAT Recovery",
		weightFactor: 1,
		createdAt: "",
		updatedAt: "",
	},
	{
		id: 7,
		phaseCode: "P7",
		phaseName: "Shipment",
		weightFactor: 0.7,
		createdAt: "",
		updatedAt: "",
	},
	{
		id: 8,
		phaseCode: "P8",
		phaseName: "Site Acceptance Test and Commisioning",
		weightFactor: 1.5,
		createdAt: "",
		updatedAt: "",
	},
	{
		id: 9,
		phaseCode: "P9",
		phaseName: "Service Handover",
		weightFactor: 0.7,
		createdAt: "",
		updatedAt: "",
	},
];
